import type {
  Agent,
  AgentDetail,
  AgentObservation,
  BootstrapEnvelope,
  ConversationDirectory,
  DriverReport,
  InboxItem,
  PluginState,
  RunSnapshot,
} from "./contracts";

export const previewDirectory: ConversationDirectory = {
  activeConversationId: "symphony-harness",
  groups: [
    {
      id: "symphony",
      title: "Symphony",
      conversations: [
        {
          id: "symphony-harness",
          groupId: "symphony",
          title: "Build Symphony agent harness",
          updatedLabel: "now",
          updatedAt: "2026-08-30T01:18:02.000Z",
          state: "running",
          pinned: true,
          loader: "circular",
          conductorAgentId: "conductor",
          workspacePath: "symphony / local",
        },
        {
          id: "native-adapters",
          groupId: "symphony",
          title: "Design native harness adapters",
          updatedLabel: "18m",
          updatedAt: "2026-08-30T00:56:00.000Z",
          state: "attention",
          pinned: false,
          unread: true,
          loader: "square",
        },
        {
          id: "model-routing",
          groupId: "symphony",
          title: "Research neutral model routing",
          updatedLabel: "2h",
          updatedAt: "2026-08-29T23:40:00.000Z",
          state: "completed",
          pinned: false,
        },
        {
          id: "workflow-dsl",
          groupId: "symphony",
          title: "Specify dynamic workflow files",
          updatedLabel: "yesterday",
          updatedAt: "2026-08-29T12:00:00.000Z",
          state: "idle",
          pinned: false,
        },
      ],
    },
    {
      id: "rebalance",
      title: "Rebalancer",
      conversations: [
        {
          id: "railway-usage",
          groupId: "rebalance",
          title: "Optimize Railway usage",
          updatedLabel: "3h",
          updatedAt: "2026-08-29T22:40:00.000Z",
          state: "running",
          pinned: false,
          loader: "triangle",
        },
        {
          id: "dashboard-500",
          groupId: "rebalance",
          title: "Fix dashboard 500",
          updatedLabel: "Fri",
          updatedAt: "2026-08-28T16:00:00.000Z",
          state: "completed",
          pinned: false,
        },
      ],
    },
    {
      id: "synthcave",
      title: "Synthcave",
      conversations: [
        {
          id: "multi-note-drag",
          groupId: "synthcave",
          title: "Add multi-note drag behavior",
          updatedLabel: "Tue",
          updatedAt: "2026-08-25T18:00:00.000Z",
          state: "idle",
          pinned: false,
        },
        {
          id: "synth-research",
          groupId: "synthcave",
          title: "Research synth notes and BPMs",
          updatedLabel: "Mon",
          updatedAt: "2026-08-24T18:00:00.000Z",
          state: "completed",
          pinned: false,
        },
      ],
    },
  ],
};

const previewAgents: Agent[] = [
  {
    id: "conductor",
    depth: 0,
    name: "Conductor",
    objective: "Deliver the vertical slice and keep every worker aligned.",
    model: "gpt-5.6-sol",
    harness: "Pi",
    access: "full-access",
    state: "running",
    nativeStatus: "running",
    elapsed: "18m 42s",
    cost: 0.62,
    lastActivity: "now",
    nativeSessionId: "pi_sess_conductor",
    workspacePath: "/Users/justus/Documents/Programming/Symphony",
    runId: "run_local_01J7",
    workflowId: "chat:symphony-harness",
  },
  {
    id: "builder",
    parentId: "conductor",
    depth: 1,
    name: "Native adapter",
    objective: "Implement the native Codex adapter and lifecycle bridge.",
    model: "gpt-5.6-sol",
    harness: "Codex",
    access: "full-access",
    state: "running",
    nativeStatus: "running",
    elapsed: "11m 08s",
    cost: 0.74,
    lastActivity: "12s",
    nativeSessionId: "codex_thread_builder",
    nativeRunId: "turn_18",
    workspacePath: "/Users/justus/Documents/Programming/Symphony",
    runId: "run_local_01J7",
    workflowId: "chat:symphony-harness",
  },
  {
    id: "documenter",
    parentId: "conductor",
    depth: 1,
    name: "Lifecycle notes",
    objective: "Document lifecycle edge cases for adapter consumers.",
    model: "claude-sonnet-4.6",
    harness: "Claude Code",
    access: "read-only",
    state: "waiting",
    nativeStatus: "waiting",
    elapsed: "05m 31s",
    cost: 0.31,
    lastActivity: "1m",
    nativeSessionId: "claude_sess_notes",
    output: {
      findings: ["Reconnect preserves the native session.", "Cancellation acknowledgement needs an explicit event."],
    },
    runId: "run_local_01J7",
    workflowId: "chat:symphony-harness",
  },
  {
    id: "observer",
    parentId: "builder",
    depth: 2,
    name: "Observer",
    objective: "Summarize the builder transcript at paragraph granularity.",
    model: "glm-5.3-flash",
    harness: "OpenCode",
    access: "read-only",
    state: "succeeded",
    nativeStatus: "completed",
    elapsed: "00m 19s",
    cost: 0.02,
    lastActivity: "2m",
    nativeSessionId: "opencode_obs_1",
    runId: "run_local_01J7",
    workflowId: "chat:symphony-harness",
  },
];

export const previewSnapshot: RunSnapshot = {
  runId: "run_local_01J7",
  workflowId: "chat:symphony-harness",
  workspace: "symphony / local",
  mode: "preview",
  mission: {
    id: "chat:symphony-harness",
    statement:
      "Ship the first reliable Symphony vertical slice: launch native coding agents, observe them without interruption, and verify their output from one command center.",
    keyResults: [
      "Native sessions remain unmodified",
      "Every child inherits mission revision 07",
      "Agent activity remains observable without interruption",
    ],
    revision: "07",
    hash: "preview-mission-07",
  },
  phase: "Adapter implementation",
  cost: {
    amount: 1.84,
    currency: "USD",
    provenance: "estimated",
    knownTotal: 1.69,
    unknownEvents: 1,
    eventCount: 6,
    byBasis: {
      "harness-reported": 0.93,
      "token-priced-estimate": 0.76,
    },
  },
  agents: previewAgents,
  nodes: [
    {
      id: "brief",
      label: "Mission brief",
      detail: "rev 07 locked",
      agentId: "conductor",
      state: "succeeded",
      x: 48,
      y: 154,
    },
    {
      id: "adapter",
      label: "Native adapter",
      detail: "Codex lifecycle bridge",
      agentId: "builder",
      state: "running",
      x: 266,
      y: 70,
    },
    {
      id: "observation",
      label: "Passive observation",
      detail: "paragraph checkpoint",
      agentId: "observer",
      state: "succeeded",
      x: 267,
      y: 238,
    },
    {
      id: "notes",
      label: "Lifecycle notes",
      detail: "edge cases documented",
      agentId: "documenter",
      state: "waiting",
      x: 489,
      y: 70,
    },
    {
      id: "release",
      label: "Complete slice",
      detail: "waiting on active work",
      state: "blocked",
      x: 489,
      y: 238,
    },
  ],
  edges: [
    { from: "brief", to: "adapter", kind: "delegation" },
    { from: "brief", to: "observation", kind: "delegation" },
    { from: "adapter", to: "notes", kind: "dependency" },
    { from: "observation", to: "release", kind: "dependency" },
    { from: "notes", to: "release", kind: "dependency" },
  ],
  events: [
    {
      id: "evt-1",
      at: "2:36 PM",
      occurredAt: "2026-08-30T14:36:04.000Z",
      kind: "observation",
      title: "Lifecycle notes updated",
      detail: "Reconnect behavior is documented; cancellation acknowledgement still needs an explicit event.",
      agentId: "documenter",
      nodeId: "notes",
      source: "agent-reported",
    },
    {
      id: "evt-2",
      at: "2:35 PM",
      occurredAt: "2026-08-30T14:35:42.000Z",
      kind: "message",
      title: "Conductor sent one correction",
      detail: "Scope: builder only · preserve the native session and repair cancellation semantics.",
      agentId: "builder",
      nodeId: "adapter",
      source: "runtime-observed",
    },
    {
      id: "evt-3",
      at: "2:34 PM",
      occurredAt: "2026-08-30T14:34:17.000Z",
      kind: "tool",
      title: "Builder changed 3 files",
      detail: "adapter/codex.ts · events/normalize.ts · adapter/codex.test.ts",
      agentId: "builder",
      nodeId: "adapter",
      source: "runtime-observed",
    },
    {
      id: "evt-4",
      at: "2:33 PM",
      occurredAt: "2026-08-30T14:33:51.000Z",
      kind: "system",
      title: "Observer checkpoint stored",
      detail: "Builder is implementing lifecycle translation; no scope drift detected.",
      agentId: "observer",
      nodeId: "observation",
      source: "runtime-observed",
    },
  ],
  runStatus: "running",
};

export const previewDrivers: DriverReport[] = [
  {
    driver: "pi",
    available: true,
    authenticated: true,
    version: "0.52.1",
    detail: "Pi RPC is ready for the conductor.",
    capabilities: {
      streaming: true,
      resume: true,
      steer: true,
      passiveHistory: true,
      usage: true,
      mcp: true,
      local: true,
      cloud: false,
      readOnly: true,
    },
  },
  {
    driver: "codex",
    available: true,
    authenticated: true,
    version: "0.48.0",
    detail: "Codex App Server is reachable over stdio.",
    capabilities: {
      streaming: true,
      resume: true,
      steer: true,
      passiveHistory: true,
      usage: true,
      mcp: true,
      local: true,
      cloud: false,
      readOnly: true,
    },
  },
  {
    driver: "claude",
    available: true,
    authenticated: true,
    version: "2.1.4",
    detail: "Claude Agent SDK can launch a native session.",
    capabilities: {
      streaming: true,
      resume: true,
      steer: true,
      passiveHistory: true,
      usage: true,
      mcp: true,
      local: true,
      cloud: false,
      readOnly: true,
    },
  },
  {
    driver: "cursor",
    available: true,
    authenticated: false,
    version: "1.6.0",
    detail: "Cursor SDK is installed. Cloud Agents need CURSOR_API_KEY or a native login.",
    capabilities: {
      streaming: true,
      resume: true,
      steer: true,
      passiveHistory: true,
      usage: true,
      mcp: true,
      local: true,
      cloud: true,
      readOnly: true,
    },
  },
  {
    driver: "opencode",
    available: true,
    authenticated: true,
    version: "1.1.8",
    detail: "OpenCode server is listening locally.",
    capabilities: {
      streaming: true,
      resume: true,
      steer: true,
      passiveHistory: true,
      usage: true,
      mcp: true,
      local: true,
      cloud: false,
      readOnly: true,
    },
  },
];

export const previewPlugins: PluginState[] = [];

export const previewInbox: InboxItem[] = [
  {
    id: "inbox-lifecycle",
    conversationId: "symphony-harness",
    agentId: "documenter",
    title: "Lifecycle edge case needs attention",
    detail: "Cancellation acknowledgement needs one explicit event in the adapter contract.",
    at: "2:36 PM",
    severity: "attention",
    read: false,
  },
  {
    id: "inbox-adapters",
    conversationId: "native-adapters",
    title: "Native adapters need a decision",
    detail: "The conductor is waiting on whether Cursor Cloud is in scope for v1.",
    at: "18m",
    severity: "attention",
    read: false,
  },
];

const previewObservations: Record<string, Partial<Record<AgentObservation["level"], AgentObservation>>> = {
  builder: {
    tldr: {
      level: "tldr",
      summary: "Codex is translating native lifecycle events. Cancellation acknowledgement is the remaining gap.",
      generatedBy: "model",
      model: "glm-5.3-flash",
    },
    paragraph: {
      level: "paragraph",
      summary:
        "The adapter is translating native lifecycle events without changing the Codex session. Reconnect and resume look correct. Cancellation acknowledgement still needs one explicit event before the slice is complete.",
      generatedBy: "model",
      model: "glm-5.3-flash",
    },
    full: {
      level: "full",
      summary:
        "session.started → turn.started → file edits on adapter/codex.ts, events/normalize.ts, adapter/codex.test.ts. usage.recorded for the current turn. No mission drift. Native session id preserved across the correction.",
      generatedBy: "deterministic",
      model: null,
    },
  },
  documenter: {
    tldr: {
      level: "tldr",
      summary: "Lifecycle edge cases are documented. One cancellation event remains ambiguous.",
      generatedBy: "model",
      model: "glm-5.3-flash",
    },
  },
  observer: {
    tldr: {
      level: "tldr",
      summary: "Builder is implementing lifecycle translation; no scope drift detected.",
      generatedBy: "deterministic",
      model: null,
    },
  },
};

export function previewAgentDetail(agentId: string): AgentDetail | null {
  const agent = previewAgents.find((item) => item.id === agentId);
  if (!agent) return null;
  const parent = agent.parentId ? previewAgents.find((item) => item.id === agent.parentId) : undefined;
  const children = previewAgents.filter((item) => item.parentId === agent.id);
  return {
    ...agent,
    parent,
    children,
    observations: previewObservations[agent.id] ?? {},
    files:
      agent.id === "builder"
        ? [
            { path: "packages/drivers/src/codex.ts", detail: "lifecycle bridge" },
            { path: "packages/drivers/src/common.ts", detail: "event normalize" },
            { path: "packages/drivers/src/codex.test.ts", detail: "contract tests" },
          ]
        : [],
    artifacts:
      agent.id === "documenter"
        ? [{ id: "lifecycle-notes", label: "Lifecycle edge-case notes" }]
        : [],
  };
}

export function previewEnvelope(): BootstrapEnvelope {
  return {
    apiVersion: 1,
    runtimeEpoch: "preview",
    cursor: 0,
    events: [],
    mode: "preview",
    directory: previewDirectory,
    run: previewSnapshot,
    threads: [],
    messages: [],
    projects: [
      {
        id: "symphony",
        title: "Symphony",
        workspacePath: "/Users/justus/Documents/Programming/Symphony",
        isGitRepository: true,
        createdAt: "2026-08-30T01:00:00.000Z",
        updatedAt: "2026-08-30T01:18:02.000Z",
      },
    ],
    agents: [],
    runs: [],
    costs: previewSnapshot.cost,
    runCosts: { [previewSnapshot.runId]: previewSnapshot.cost },
    agentCosts: Object.fromEntries(previewAgents.map((agent) => [agent.id, {
      amount: agent.cost,
      currency: "USD",
      provenance: "estimated" as const,
    }])),
    plugins: previewPlugins,
    drivers: previewDrivers,
    models: [
      { id: "gpt-5.6-sol", harness: "pi", name: "GPT-5.6 Sol" },
      { id: "claude-sonnet-4.6", harness: "claude", name: "Claude Sonnet 4.6" },
      { id: "glm-5.3-flash", harness: "opencode", name: "GLM 5.3 Flash" },
    ],
    settings: {
      configPath: "symphony.config.json",
      conductor: { harness: "pi", model: "auto" },
      agents: { maxDepth: 3, maxConcurrent: 8, defaultPermissions: "full-access" },
    },
    inbox: previewInbox,
    daemon: {
      version: "0.1.0",
      startedAt: "2026-08-30T01:00:00.000Z",
      noPlugins: false,
    },
  };
}
